### ISSUE TITLE
Error 117

### ISSUE THREAD

**Issue by Murzar** [tmxkn1/D-OS-Save-Editor#14]
Getting a error of 'Error 117' while trying to load (in-game) the edited save.

Tried all combinations while editing stats, with various increments. Even just changing one attribute value by 1 point gives that error.

**Comment by AnthonyZJiang** [comment]
I haven't played the game for a while. Can you confirm your game version and mods please?

**Comment by Murzar** [comment]
Oops sorry.. completely forgot
Version - 2.0.99.113
Mods - None

**Comment by AnthonyZJiang** [comment]
You are using an old game version while the edited savegame will only work with game ver. 2.0.119.430, i.e. the latest steam version. Can you upgrade your game?

**Comment by Murzar** [comment]
I can but I would like to avoid. I was in a middle of a play through and stopped since January (starting again). I usually block all updates till I finish my play through or if there's a game breaking bug.  

Can you recommend a version of your tool that will work with the version of my game?

**Comment by AnthonyZJiang** [comment]
All versions of my tool are built for the latest game. You may try [Moose editor](http://larian.com/forums/ubbthreads.php?ubb=showflat&Number=521295#Post521295).

BTW, I believe it is pretty safe to upgrade your game and continue to play your old savegame..
