### ISSUE TITLE
Learning Skills

### ISSUE THREAD

**Issue by StormBloodfallen** [tmxkn1/D-OS-Save-Editor#18]
I haven't seen anybody else address this issue yet so I'll be the first I guess. If you modify the skill level (like Pyrokinetic 1 changed to Pyrokinetic 5) the game recognizes that the level has been changed and does not allow for a skillbook to be learned that is outside of the base game parameters. However, if the level is modified the game recognizes the modified level as an "earned" level (so you can change level to learn skillbooks requiring a higher level.) This means that if you are level 1, and would like to learn Meteor Shower, the character level is not a problem but the Pyrokinetic skill level is a problem.

**Comment by AnthonyZJiang** [comment]
_Change Pyurokinetic lv1 to lv5 enables your character to learn a skillbook such Meteor Shower.
Change Pyurokinetic lv0 to lv5 won't do the same because lv5 is recoginised as an earned level._

Is this what you were saying?

**Comment by StormBloodfallen** [comment]
From my understanding, changing Pyrokinetic lv1 to lv 5 **should** enable the character to learn a skillbook. Unfortunately, this doesn't work. I'll play through and take screenshots to post.

**Comment by StormBloodfallen** [comment]
I found the problem, I was using an old version of the system. The v1.5.5 had the problem but the current alpha version doesn't. Turns out I just had to update to an improved version.
