### ISSUE TITLE
Talents an Ability Effects

### ISSUE THREAD

**Issue by Greavox** [tmxkn1/D-OS-Save-Editor#6]
Maybe can use : [https://github.com/mishley/MooseEdit/blob/enhanced-edition/parsed_talents.txt](https://github.com/mishley/MooseEdit/blob/enhanced-edition/parsed_talents.txt) to legend talents choices in the new Talents tab with ToolTip? (With minor arrangement of course)

**Comment by Greavox** [comment]
I test to implement this in this moment for Abilities an Talent Tab. I'll keep you informed^^
![sans titre](https://user-images.githubusercontent.com/35181101/39707815-c08804c0-5215-11e8-8b5f-52c134daaf2c.jpg)

**Comment by tmxkn1** [comment]
Awesome, thank you for your contribution. :D

**Comment by FlukiestEmperor** [comment]
It would also be useful to build the talent tab from a list of talents. Right now the view for talents cannot change at all since the position of each talent is essentially its id.

**Comment by Greavox** [comment]
> It would also be useful to build the talent tab from a list of talents. Right now the view for talents cannot change at all since the position of each talent is essentially its id. @FlukiestEmperor 

I'm okay with you. I would do it but my C# skill is very very low/bad, worse my English writing that is bad too ^^ With [https://raw.githubusercontent.com/mishley/MooseEdit/enhanced-edition/parsed_talents.txt](https://raw.githubusercontent.com/mishley/MooseEdit/enhanced-edition/parsed_talents.txt), I saw Talents isn't in D OS Editor like "Weather the Storm" by example. How can you see this list in a savegame ? I'm lost in code file :$

> Also, what do you guys think about talents that are no longer obtainable in game? Should those be a different color?

Yes, it's great idea ! It's better that show an eye on Tooltip. I woult do it too, but I don't know how to do like class/id ith selector from CSS

**Comment by FlukiestEmperor** [comment]
@Greavox I don't know anything about the history of this game, but that file was last committed nearly 4  years ago so the creators of the game must've removed, modified and added skills since then.

**Comment by Greavox** [comment]
I know that, but I was talking about the fact to load Talents value from savegame (I didn't find that in code - I'm noob, sorry ^^)

**Comment by tmxkn1** [comment]
> It would also be useful to build the talent tab from a list of talents. Right now the view for talents cannot change at all since the position of each talent is essentially its id.
We store talent ids in `Tag` properties and access them from there. Then we can change the view.

> I saw Talents isn't in D OS Editor like "Weather the Storm" by example. How can you see this list in a savegame ?
I don't think you can see talent names in a savegame file. Talents are stored as bits in three 2^32 arrays; these arrays are then converted to three seperate uints to be saved in a savegame file.

> I know that, but I was talking about the fact to load Talents value from savegame
Me too, which is why I didn't add the function. I don't know much about C/C++.

**Comment by tmxkn1** [comment]
> If you tell how to do for one, I will do the rest ^^

What you could do is search for `<CheckBox ` and replace it with `<CheckBox Tag="" `. Then you will have to manually fill all the empty tags. There are 80 of them, so don't worry, I will build it from a list. It will be neater and easier to manage. Thanks anyway :D

**Comment by tmxkn1** [comment]
![1](https://user-images.githubusercontent.com/8778250/39729139-30dd60a8-5252-11e8-9c9c-43a1eda95412.png)
![2](https://user-images.githubusercontent.com/8778250/39729141-3257d666-5252-11e8-8627-19db9fcf519a.png)

Talent checkboxes are now loaded from lists and can be sorted in order. In the above image, they are ordered by IsHidden first then name in alphabetic order. Looks ugly, but is easier for one to locate a talent if the name is known. Maybe the hidden talents should be arranged in separate columns.

**Comment by tmxkn1** [comment]
![1](https://user-images.githubusercontent.com/8778250/39730153-e12adbac-5257-11e8-8066-020e8f85a4c3.png)

This looks better I guess.

**Comment by Greavox** [comment]
Good idea and great work !

**Comment by Greavox** [comment]
Hi ^^
And now same work with Abilities Tab
![sans-titre-1](https://user-images.githubusercontent.com/35181101/39781839-9cf72512-5310-11e8-929e-30715e52bac8.jpg)
The DataTable file was modified by adding a "string array" wich each ability grouped by 3 like this :
1. Name of Variable that used like Bow or SingleHanded
2. Name of Ability like InGame example Bow or Single-Handed
3. Description of Ability like InGame example "Bow increases the damage you do using bows."

UpdateForm() and SaveEdits() from AbilitiesTab were reduced to become more dynamically with DataTable "like" TalentsTab. To do that, each TextBlock received a X:Name.

Unknown Abilities were keeped PlaceHolderX (X is int between 2 and 5 included) : I don't see difference in Player Info when I select them in game

Feel free to change code : I'm newbie on C# and I'm far from PHP 😅

**Comment by tmxkn1** [comment]
Sounds cool. Let me have a look before I go to bed :D
